BEGIN;
-- MERGE-PUHASTUS-PASS: 15 üle-fragment merge (väljundi-test kinnitatud)
UPDATE product_category_product SET product_category_id='pcat_mv_6x6_4' WHERE product_category_id='pcat_mv_6x6_5';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_mv_6x6_5';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_mv_6x6_5';
UPDATE product_category_product SET product_category_id='pcat_el_11x9_1' WHERE product_category_id='pcat_el_11x9_3';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_el_11x9_3';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_el_11x9_3';
UPDATE product_category_product SET product_category_id='pcat_ks_4x4_3' WHERE product_category_id='pcat_ks_4x4_1';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_ks_4x4_1';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_ks_4x4_1';
UPDATE product_category_product SET product_category_id='pcat_t3f_1_27' WHERE product_category_id='pcat_t3f_1_31';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_t3f_1_31';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_t3f_1_31';
UPDATE product_category_product SET product_category_id='pcat_ks_4x3_2' WHERE product_category_id='pcat_ks_4x3_4';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_ks_4x3_4';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_ks_4x3_4';
UPDATE product_category_product SET product_category_id='pcat_mv_6x1_2' WHERE product_category_id='pcat_mv_6x1_3';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_mv_6x1_3';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_mv_6x1_3';
UPDATE product_category SET name='Mööblijalad', updated_at=now() WHERE id='pcat_mv_6x1_2';
UPDATE product_category_product SET product_category_id='pcat_ag2_2x6_4' WHERE product_category_id='pcat_ag2_2x6_5';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_ag2_2x6_5';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_ag2_2x6_5';
UPDATE product_category_product SET product_category_id='pcat_ag2_2x6_6' WHERE product_category_id='pcat_2align';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_2align';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_2align';
UPDATE product_category_product SET product_category_id='pcat_ag2_2x2_1' WHERE product_category_id='pcat_mv_6x2_23';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_mv_6x2_23';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_mv_6x2_23';
UPDATE product_category_product SET product_category_id='pcat_es_10x5_7' WHERE product_category_id='pcat_es_10x5_6';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_es_10x5_6';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_es_10x5_6';
UPDATE product_category_product SET product_category_id='pcat_f4_17x3_1' WHERE product_category_id='pcat_f4_17x3_5';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_f4_17x3_5';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_f4_17x3_5';
UPDATE product_category_product SET product_category_id='pcat_mv_8x2_3' WHERE product_category_id='pcat_mv_8x2_2';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_mv_8x2_2';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_mv_8x2_2';
UPDATE product_category_product SET product_category_id='pcat_ks_5x1_4' WHERE product_category_id='pcat_5warm';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_5warm';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_5warm';
UPDATE product_category SET name='Toidusoojendajad ja bain-marie', updated_at=now() WHERE id='pcat_ks_5x1_4';
UPDATE product_category_product SET product_category_id='pcat_t3f_10_22' WHERE product_category_id='pcat_t3f_10_19';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_t3f_10_19';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_t3f_10_19';
UPDATE product_category_product SET product_category_id='pcat_mv_8x1_4' WHERE product_category_id='pcat_mv_8x1_3';
DELETE FROM taxonomy_node_meta WHERE node_id='pcat_mv_8x1_3';
UPDATE product_category SET deleted_at=now(), updated_at=now() WHERE id='pcat_mv_8x1_3';
-- re-compact L3-rank puudutatud L2-des (merge-augu parand)
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l6_6' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l11_9' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l4_4' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_t3l2_1' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l4_3' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_6osad' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l2_6' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_22shelf' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l10_5' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l17_3' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l8_2' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_5hold' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_t3l2_10' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
WITH r AS (SELECT id, row_number() OVER (ORDER BY rank, name) rn FROM product_category WHERE parent_category_id='pcat_v4_l8_1' AND deleted_at IS NULL) UPDATE product_category p SET rank=r.rn, updated_at=now() FROM r WHERE p.id=r.id;
COMMIT;
