// AUTO-GENERATED — do not edit by hand.
// Source: backend/src/data/taxonomy.yaml
// Regenerate: node scripts/gen-branches.mjs

export type BranchDef = {
  name: string
  nameEn: string
  slug: string
  categoryHandle: string | null
  tagline: string
  taglineEn: string
  description: string
  heroImg: string
  heroGradient: string
}

export const BRANCHES: BranchDef[] = [
  {
    name: "Suurköök ja Toitlustus",
    nameEn: "HoReCa & Food Service",
    slug: "horeca",
    categoryHandle: "horeca-food-service",
    tagline: "Professionaalne köök algab õigest varustusest",
    taglineEn: "The professional kitchen starts with the right equipment",
    description: "Roostevaba terasest tööpinnad, kuumseadmed, külmikud, cateringitehnika ja serveerimisvahendid professionaalsele köögile ja toitlustusettevõttele.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-amber-950/80 via-amber-900/40 to-transparent",
  },
  {
    name: "Laser-, CNC- ja digitaaltootmine",
    nameEn: "Laser, CNC & Digital Fabrication",
    slug: "laser-cnc",
    categoryHandle: "laser-cnc-digital-fabrication",
    tagline: "Täppistootmine uuel tasemel",
    taglineEn: "Precision manufacturing, next level",
    description: "Lasergraveerijad, CNC-freesid, 3D-printerid ja digitaaltootmise seadmed täppistöödeks ja prototüüpimiseks.",
    heroImg: "/images/branches/laser-cnc.webp",
    heroGradient: "from-violet-950/80 via-violet-900/40 to-transparent",
  },
  {
    name: "Keevitus ja metallitööd",
    nameEn: "Welding & Metalworking",
    slug: "keevitus",
    categoryHandle: "welding-metalworking",
    tagline: "Metallist meistritööd",
    taglineEn: "Masterwork in metal",
    description: "Keevitusaparaadid, lõikurid, painutuspingid ja metallitöötluse seadmed. Professionaalsed lahendused metallitöökojale.",
    heroImg: "/images/branches/keevitus.webp",
    heroGradient: "from-red-950/80 via-red-900/40 to-transparent",
  },
  {
    name: "Trükk, pakendamine ja silt",
    nameEn: "Printing, Packaging & Signage",
    slug: "trukk-pakendamine",
    categoryHandle: "printing-packaging-signage",
    tagline: "Sinu bränd, sinu visuaal",
    taglineEn: "Your brand, your visual",
    description: "Trükimasinad, pakendamisseadmed, vinüülilõikurid ja reklaamtehnika. Professionaalsed lahendused brändingu ja reklaami jaoks.",
    heroImg: "/images/branches/trukk-pakendamine.webp",
    heroGradient: "from-fuchsia-950/80 via-fuchsia-900/40 to-transparent",
  },
  {
    name: "Elekter ja energia",
    nameEn: "Electrical & Energy",
    slug: "elekter-energia",
    categoryHandle: "electrical-energy",
    tagline: "Energia igale vajadusele",
    taglineEn: "Power for every need",
    description: "Generaatorid, inverterid, päikesepaneelid, akud ja elektripaigaldustarvikud. Energialahendused igale vajadusele.",
    heroImg: "/images/branches/elekter-energia.webp",
    heroGradient: "from-blue-950/80 via-blue-900/40 to-transparent",
  },
  {
    name: "Puidutöö ja tisler",
    nameEn: "Woodworking & Carpentry",
    slug: "puidutoo",
    categoryHandle: "woodworking-carpentry",
    tagline: "Puit väärib parimat töötlust",
    taglineEn: "Wood deserves the finest craftsmanship",
    description: "Höövlid, saepingid, freesid ja puidutöötlemise seadmed. Kõik vajalik kvaliteetseks tisleritööks ja puusepatöökojale.",
    heroImg: "/images/branches/puidutoo.webp",
    heroGradient: "from-yellow-950/80 via-yellow-900/40 to-transparent",
  },
  {
    name: "Ehitus",
    nameEn: "Construction & Building",
    slug: "ehitus",
    categoryHandle: "construction-building",
    tagline: "Ehita nagu profi",
    taglineEn: "Build like a pro",
    description: "Lõikurid, tõstukid, tellingud, mõõteriistad ja ehituskeemia. Kõik tööriistad ja seadmed ehitusplatsile ning renoveerimistöödeks.",
    heroImg: "/images/branches/ehitus.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Puhastus ja hoolduskemia",
    nameEn: "Cleaning & Janitorial",
    slug: "puhastus",
    categoryHandle: "cleaning-janitorial",
    tagline: "Puhtus on professionaalsuse alus",
    taglineEn: "Cleanliness is the foundation of professionalism",
    description: "Professionaalsed survepesured, põrandahooldusmasinad, tolmuimejad ja puhastusvahendid. Tööstuslik puhtus mõistliku hinnaga.",
    heroImg: "/images/branches/puhastus.webp",
    heroGradient: "from-teal-950/80 via-teal-900/40 to-transparent",
  },
  {
    name: "Käsi- ja elektritööriistad",
    nameEn: "Hand & Power Tools",
    slug: "tooriistad",
    categoryHandle: "hand-power-tools",
    tagline: "Igale tööle õige tööriist",
    taglineEn: "The right tool for every job",
    description: "Akutrellid, lihvmasinad, saed, mutrivõtmed ja muud käsi- ning elektritööriistad igapäevaseks ja professionaalseks kasutamiseks.",
    heroImg: "/images/branches/tooriistad.webp",
    heroGradient: "from-orange-950/80 via-orange-900/40 to-transparent",
  },
  {
    name: "Kütus ja määrdeained",
    nameEn: "Fuel, Lubrication & Fluid Management",
    slug: "kutus-vedelikud",
    categoryHandle: "fuel-lubrication-fluid",
    tagline: "Vedelike käitlemine turvaliselt",
    taglineEn: "Fluid management done safely",
    description: "Kütuseülekande pumbad, määrdepressid, vedelike kogumisseadmed ja mahutid. Turvaline ja efektiivne vedelike käitlemine.",
    heroImg: "/images/branches/kutus-vedelikud.webp",
    heroGradient: "from-amber-950/80 via-amber-900/40 to-transparent",
  },
  {
    name: "Haljastus ja õuetehnika",
    nameEn: "Outdoor Power & Landscaping",
    slug: "aiatehnika",
    categoryHandle: "outdoor-power-landscaping",
    tagline: "Professionaalne haljastus ja aiandus",
    taglineEn: "Professional landscaping and gardening",
    description: "Niidukid, trimmerd, pumpad, kasvuhooned ja maastikuhoolduse seadmed. Professionaalne varustus aia ja haljasalade hoolduseks.",
    heroImg: "/images/branches/aiatehnika.webp",
    heroGradient: "from-emerald-950/80 via-emerald-900/40 to-transparent",
  },
  {
    name: "Laondus ja käitlus",
    nameEn: "Warehousing & Material Handling",
    slug: "laondus",
    categoryHandle: "warehousing-material-handling",
    tagline: "Ladu korras, töö sujub",
    taglineEn: "Organized warehouse, smooth operations",
    description: "Riiulisüsteemid, tõstukid, kärud ja ladustamisseadmed. Kõik vajalik lao efektiivseks haldamiseks ja materjalide käitlemiseks.",
    heroImg: "/images/branches/laondus.webp",
    heroGradient: "from-slate-950/80 via-slate-900/40 to-transparent",
  },
  {
    name: "Ventilatsioon ja kliimakontroll",
    nameEn: "HVAC & Climate Control",
    slug: "kliima",
    categoryHandle: "hvac-climate-control",
    tagline: "Mugav kliima igas ruumis",
    taglineEn: "Comfortable climate in every room",
    description: "Konditsioneerid, soojuspumbad, ventilaatorid ja õhukvaliteedi seadmed. Mugav sisekliima nii kodus kui kontoris.",
    heroImg: "/images/branches/kliima.webp",
    heroGradient: "from-sky-950/80 via-sky-900/40 to-transparent",
  },
  {
    name: "Veevärk ja santehnika",
    nameEn: "Plumbing & Water Systems",
    slug: "torustik",
    categoryHandle: "plumbing-water-systems",
    tagline: "Vesi voolab sinna, kuhu vaja",
    taglineEn: "Water flows where it's needed",
    description: "Torupressid, pumpad, filtrid ja torustiku paigaldustarvikud. Professionaalsed lahendused veevarustuse ja kanalisatsiooni jaoks.",
    heroImg: "/images/branches/torustik.webp",
    heroGradient: "from-cyan-950/80 via-cyan-900/40 to-transparent",
  },
  {
    name: "Ohutus ja tööriided",
    nameEn: "Safety, Security & Workwear",
    slug: "ohutus",
    categoryHandle: "safety-security-workwear",
    tagline: "Kaitse ennast ja oma meeskonda",
    taglineEn: "Protect yourself and your team",
    description: "Isikukaitsevahendid, turvavarustus, tööriietus ja ohutustehnika. Kõik vajalik töökoha ohutuse tagamiseks.",
    heroImg: "/images/branches/ohutus.webp",
    heroGradient: "from-rose-950/80 via-rose-900/40 to-transparent",
  },
  {
    name: "Auto ja töökoda",
    nameEn: "Automotive & Workshop",
    slug: "auto",
    categoryHandle: "automotive-workshop",
    tagline: "Sinu garaaz, sinu reeglid",
    taglineEn: "Your garage, your rules",
    description: "Tungrauad, kompressorid, diagnostikaseadmed ja autohoolduse tööriistad. Kõik profi tasemel garaazi ja töökoja jaoks.",
    heroImg: "/images/branches/auto.webp",
    heroGradient: "from-zinc-950/80 via-zinc-900/40 to-transparent",
  },
  {
    name: "Ilu- ja spaasalong",
    nameEn: "Salon, Spa & Wellness",
    slug: "salong",
    categoryHandle: "salon-spa-wellness",
    tagline: "Ilu ja heaolu professionaalile",
    taglineEn: "Beauty and wellness for the professional",
    description: "Juuksuritoolid, massaažilauad, spa-seadmed ja iluteeninduse tarvikud. Professionaalne varustus salongidele ja spa-dele.",
    heroImg: "/images/branches/salong.webp",
    heroGradient: "from-pink-950/80 via-pink-900/40 to-transparent",
  },
  {
    name: "Kontor ja sisustus",
    nameEn: "Office & Commercial Interiors",
    slug: "kontor",
    categoryHandle: "office-commercial-interiors",
    tagline: "Kontor ja äripind, targalt sisustatud",
    taglineEn: "Office and commercial space, smartly furnished",
    description: "Kontorimööbel, esitlustehnika, organiseerimissüsteemid ja äripinna sisustus. Funktsionaalne ja esinduslik töökeskkond.",
    heroImg: "/images/branches/kontor.webp",
    heroGradient: "from-gray-950/80 via-gray-900/40 to-transparent",
  },
  {
    name: "Tervishoid ja meditsiin",
    nameEn: "Health & Medical Supply",
    slug: "tervis",
    categoryHandle: "health-medical-supply",
    tagline: "Professionaalne meditsiinivarustus",
    taglineEn: "Professional medical equipment",
    description: "Meditsiiniline mööbel, diagnostikaseadmed, taastusravi vahendid ja tervishoiu tarvikud professionaalseks kasutamiseks.",
    heroImg: "/images/branches/tervis.webp",
    heroGradient: "from-green-950/80 via-green-900/40 to-transparent",
  },
  {
    name: "Sport ja vabaaeg",
    nameEn: "Fitness, Sports & Recreation",
    slug: "sport",
    categoryHandle: "fitness-sports-recreation",
    tagline: "Varusta oma spordiklubi",
    taglineEn: "Equip your sports club",
    description: "Jõusaali seadmed, treeningtarvikud, spordivarustus ja vabaaja seadmed. Kommertskvaliteet spordiklubidele ja kodujõusaalidele.",
    heroImg: "/images/branches/sport.webp",
    heroGradient: "from-red-950/80 via-red-900/40 to-transparent",
  },
  {
    name: "Paadid ja matkatarbed",
    nameEn: "Boating, Camping & Outdoor Adventure",
    slug: "paadindus-matk",
    categoryHandle: "boating-camping-outdoor",
    tagline: "Seiklus algab õigest varustusest",
    taglineEn: "Adventure starts with the right gear",
    description: "Kaatritarvikud, telgid, matkavarustus ja välivarustus. Kõik vajalik merel, metsas ja mägedes seiklemiseks.",
    heroImg: "/images/branches/paadindus-matk.webp",
    heroGradient: "from-indigo-950/80 via-indigo-900/40 to-transparent",
  },
  {
    name: "Muusika ja meelelahutus",
    nameEn: "Music & Entertainment",
    slug: "muusika",
    categoryHandle: "music-entertainment",
    tagline: "Muusika ja meelelahutus",
    taglineEn: "Music and entertainment for every venue",
    description: "Helitehnika, valgustus, DJ-seadmed ja lavavarustus. Professionaalsed lahendused üritustele ja meelelahutuskohtadele.",
    heroImg: "/images/branches/muusika.webp",
    heroGradient: "from-purple-950/80 via-purple-900/40 to-transparent",
  },
]

export function getBranchBySlug(slug: string) {
  return BRANCHES.find(
    (branch) => branch.slug === slug || branch.categoryHandle === slug,
  )
}
