// AUTO-GENERATED — do not edit by hand.
// Source: backend/src/data/taxonomy.yaml
// Regenerate: node scripts/gen-branches.mjs

export type BranchDef = {
  name: string
  nameEn: string
  slug: string
  categoryHandle: string | null
  tagline: string
  taglineEn: string
  description: string
  heroImg: string
  heroGradient: string
}

export const BRANCHES: BranchDef[] = [
  {
    name: "Tööriistad ja tarvikud",
    nameEn: "Tööriistad ja tarvikud",
    slug: "tooriistad-ja-tarvikud",
    categoryHandle: "v4-tooriistad-ja-tarvikud",
    tagline: "Tööriistad ja tarvikud",
    taglineEn: "Tööriistad ja tarvikud",
    description: "Tööriistad ja tarvikud — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Garaažiseadmed",
    nameEn: "Garaažiseadmed",
    slug: "garaaziseadmed",
    categoryHandle: "v4-garaaziseadmed",
    tagline: "Garaažiseadmed",
    taglineEn: "Garaažiseadmed",
    description: "Garaažiseadmed — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Autovaruosad ja -tarvikud",
    nameEn: "Autovaruosad ja -tarvikud",
    slug: "autovaruosad-ja-tarvikud",
    categoryHandle: "v4-autovaruosad-ja-tarvikud",
    tagline: "Autovaruosad ja -tarvikud",
    taglineEn: "Autovaruosad ja -tarvikud",
    description: "Autovaruosad ja -tarvikud — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Kodumasinad ja kodutehnika",
    nameEn: "Kodumasinad ja kodutehnika",
    slug: "kodumasinad-ja-kodutehnika",
    categoryHandle: "v4-kodumasinad-ja-kodutehnika",
    tagline: "Kodumasinad ja kodutehnika",
    taglineEn: "Kodumasinad ja kodutehnika",
    description: "Kodumasinad ja kodutehnika — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Suurköögiseadmed",
    nameEn: "Suurköögiseadmed",
    slug: "suurkoogiseadmed",
    categoryHandle: "v4-suurkoogiseadmed",
    tagline: "Suurköögiseadmed",
    taglineEn: "Suurköögiseadmed",
    description: "Suurköögiseadmed — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Mööbel ja sisustus",
    nameEn: "Mööbel ja sisustus",
    slug: "moobel-ja-sisustus",
    categoryHandle: "v4-moobel-ja-sisustus",
    tagline: "Mööbel ja sisustus",
    taglineEn: "Mööbel ja sisustus",
    description: "Mööbel ja sisustus — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Aed ja aiatehnika",
    nameEn: "Aed ja aiatehnika",
    slug: "aed-ja-aiatehnika",
    categoryHandle: "v4-aed-ja-aiatehnika",
    tagline: "Aed ja aiatehnika",
    taglineEn: "Aed ja aiatehnika",
    description: "Aed ja aiatehnika — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Varjualused, telgid ja kasvuhooned",
    nameEn: "Varjualused, telgid ja kasvuhooned",
    slug: "varjualused-telgid-ja-kasvuhooned",
    categoryHandle: "v4-varjualused-telgid-ja-kasvuhooned",
    tagline: "Varjualused, telgid ja kasvuhooned",
    taglineEn: "Varjualused, telgid ja kasvuhooned",
    description: "Varjualused, telgid ja kasvuhooned — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Ehitus, remont ja värvid",
    nameEn: "Ehitus, remont ja värvid",
    slug: "ehitus-remont-ja-varvid",
    categoryHandle: "v4-ehitus-remont-ja-varvid",
    tagline: "Ehitus, remont ja värvid",
    taglineEn: "Ehitus, remont ja värvid",
    description: "Ehitus, remont ja värvid — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Santehnika, küte ja ventilatsioon",
    nameEn: "Santehnika, küte ja ventilatsioon",
    slug: "santehnika-kute-ja-ventilatsioon",
    categoryHandle: "v4-santehnika-kute-ja-ventilatsioon",
    tagline: "Santehnika, küte ja ventilatsioon",
    taglineEn: "Santehnika, küte ja ventilatsioon",
    description: "Santehnika, küte ja ventilatsioon — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Elektritarvikud ja valgustus",
    nameEn: "Elektritarvikud ja valgustus",
    slug: "elektritarvikud-ja-valgustus",
    categoryHandle: "v4-elektritarvikud-ja-valgustus",
    tagline: "Elektritarvikud ja valgustus",
    taglineEn: "Elektritarvikud ja valgustus",
    description: "Elektritarvikud ja valgustus — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Sport ja vaba aeg",
    nameEn: "Sport ja vaba aeg",
    slug: "sport-ja-vaba-aeg",
    categoryHandle: "v4-sport-ja-vaba-aeg",
    tagline: "Sport ja vaba aeg",
    taglineEn: "Sport ja vaba aeg",
    description: "Sport ja vaba aeg — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Reklaami-, trüki- ja graveerimisseadmed",
    nameEn: "Reklaami-, trüki- ja graveerimisseadmed",
    slug: "reklaami-truki-ja-graveerimisseadmed",
    categoryHandle: "v4-reklaami-truki-ja-graveerimisseadmed",
    tagline: "Reklaami-, trüki- ja graveerimisseadmed",
    taglineEn: "Reklaami-, trüki- ja graveerimisseadmed",
    description: "Reklaami-, trüki- ja graveerimisseadmed — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Lemmikloomatarbed",
    nameEn: "Lemmikloomatarbed",
    slug: "lemmikloomatarbed",
    categoryHandle: "v4-lemmikloomatarbed",
    tagline: "Lemmikloomatarbed",
    taglineEn: "Lemmikloomatarbed",
    description: "Lemmikloomatarbed — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Põllumajandus ja loomakasvatus",
    nameEn: "Põllumajandus ja loomakasvatus",
    slug: "pollumajandus",
    categoryHandle: "v4-pollumajandus-ja-loomakasvatus",
    tagline: "Põllumajandus ja loomakasvatus",
    taglineEn: "Põllumajandus ja loomakasvatus",
    description: "Põllumajandus ja loomakasvatus — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Tervis, hooldus ja ilu",
    nameEn: "Tervis, hooldus ja ilu",
    slug: "tervis-hooldus-ja-ilu",
    categoryHandle: "v4-tervis-hooldus-ja-ilu",
    tagline: "Tervis, hooldus ja ilu",
    taglineEn: "Tervis, hooldus ja ilu",
    description: "Tervis, hooldus ja ilu — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Meditsiin ja liikumisabi",
    nameEn: "Meditsiin ja liikumisabi",
    slug: "meditsiin-ja-liikumisabi",
    categoryHandle: "v4-meditsiin-ja-liikumisabi",
    tagline: "Meditsiin ja liikumisabi",
    taglineEn: "Meditsiin ja liikumisabi",
    description: "Meditsiin ja liikumisabi — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
  {
    name: "Tööriied ja isikukaitse",
    nameEn: "Tööriied ja isikukaitse",
    slug: "tooriied-ja-isikukaitse",
    categoryHandle: "v4-tooriied-ja-isikukaitse",
    tagline: "Tööriied ja isikukaitse",
    taglineEn: "Tööriied ja isikukaitse",
    description: "Tööriied ja isikukaitse — tooted.",
    heroImg: "/images/branches/horeca.webp",
    heroGradient: "from-stone-950/80 via-stone-900/40 to-transparent",
  },
]

export function getBranchBySlug(slug: string) {
  return BRANCHES.find(
    (branch) => branch.slug === slug || branch.categoryHandle === slug,
  )
}
