/**
 * category-tree.ts — SSoT-derived category hierarchy lookups.
 *
 * Source of truth: backend/src/data/taxonomy.yaml
 *                  backend/src/data/taxonomy-image-aliases.yaml
 * Snapshot:        storefront/lib/category-tree.generated.json
 *                  (regenerated by scripts/gen-category-tree.mjs)
 *
 * Spec: docs/superpowers/specs/2026-04-18-taxonomy-final-design.md §3.5
 *
 * Every consumer (kategooriad page, MegaMenu, tooteleht breadcrumb,
 * JSON-LD, sitemap) MUST go through these helpers. Do not import
 * category-tree.generated.json directly elsewhere — the shape may change.
 */

import treeData from "./category-tree.generated.json"

export type Locale = "et" | "en"

export interface CategoryNode {
  handle: string
  name_en: string
  name_et: string
  level: 1 | 2 | 3
  parent_handle: string | null
  child_handles: string[]
  image_path: string | null
  image_source: "direct" | "alias" | "fuzzy" | "none"
}

interface TreeData {
  generated_at: string
  nodes: Record<string, CategoryNode>
  order: string[]
}

const TREE = treeData as TreeData

export function getNode(handle: string): CategoryNode | null {
  return TREE.nodes[handle] || null
}

export function nodeName(node: CategoryNode, locale: Locale): string {
  return locale === "en" ? node.name_en : node.name_et
}

export function nodeImage(node: CategoryNode | null): string | null {
  return node?.image_path ?? null
}

/** Resolve breadcrumb ancestors from root → immediate parent (excludes node itself). */
export function getAncestors(handle: string): CategoryNode[] {
  const out: CategoryNode[] = []
  let cur = getNode(handle)
  if (!cur) return out
  while (cur.parent_handle) {
    const parent = getNode(cur.parent_handle)
    if (!parent) break
    out.unshift(parent)
    cur = parent
  }
  return out
}

/** The L1 ancestor of a node (or the node itself if already L1). Returns null for unknown handle. */
export function getL1Ancestor(handle: string): CategoryNode | null {
  let cur = getNode(handle)
  while (cur) {
    if (cur.level === 1) return cur
    if (!cur.parent_handle) return null
    cur = getNode(cur.parent_handle)
  }
  return null
}

/** Siblings under the same parent, excluding the node itself. */
export function getSiblings(handle: string): CategoryNode[] {
  const node = getNode(handle)
  if (!node || !node.parent_handle) return []
  const parent = getNode(node.parent_handle)
  if (!parent) return []
  return parent.child_handles
    .filter((h) => h !== handle)
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null)
}

/** Direct children (L3 row when called from an L2 page). */
export function getChildren(handle: string): CategoryNode[] {
  const node = getNode(handle)
  if (!node) return []
  return node.child_handles
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null)
}

/** All L1 nodes in YAML order. */
export function getAllL1(): CategoryNode[] {
  return TREE.order
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null && n.level === 1)
}

/** Build the canonical breadcrumb trail for any handle — root → node inclusive. */
export function getBreadcrumbTrail(
  handle: string,
  locale: Locale
): Array<{ handle: string; name: string }> {
  const node = getNode(handle)
  if (!node) return []
  const out: Array<{ handle: string; name: string }> = []
  for (const a of getAncestors(handle)) {
    out.push({ handle: a.handle, name: nodeName(a, locale) })
  }
  out.push({ handle: node.handle, name: nodeName(node, locale) })
  return out
}

/**
 * Find the first handle from a candidate list that exists in the SSoT tree.
 * Used by the product page to pick a valid v3 handle from a product's
 * category_handles array (which may contain legacy strings).
 */
export function firstKnownHandle(candidates: string[]): CategoryNode | null {
  for (const h of candidates) {
    const node = getNode(h)
    if (node) return node
  }
  return null
}

/**
 * Total node count — useful for CI checks.
 */
export function totalNodes(): number {
  return TREE.order.length
}
