/**
 * category-tree.ts — SSoT-derived category hierarchy lookups.
 *
 * Source of truth: backend/src/data/taxonomy.yaml
 *                  backend/src/data/taxonomy-image-aliases.yaml
 * Snapshot:        storefront/lib/category-tree.generated.json
 *                  (regenerated by scripts/gen-category-tree.mjs)
 *
 * Spec: docs/superpowers/specs/2026-04-18-taxonomy-final-design.md §3.5
 *
 * Every consumer (kategooriad page, MegaMenu, tooteleht breadcrumb,
 * JSON-LD, sitemap) MUST go through these helpers. Do not import
 * category-tree.generated.json directly elsewhere — the shape may change.
 */

import treeData from "./category-tree.generated.json"

export type Locale = "et" | "en"

export interface CategoryNode {
  handle: string
  name_en: string
  name_et: string
  level: number
  parent_handle: string | null
  child_handles: string[]
  image_path: string | null
  image_source: "direct" | "alias" | "fuzzy" | "none"
  description_et?: string | null
  description_en?: string | null
  tagline_et?: string | null
  tagline_en?: string | null
}

interface TreeData {
  generated_at: string
  nodes: Record<string, CategoryNode>
  order: string[]
}

const TREE = treeData as TreeData

export function getNode(handle: string): CategoryNode | null {
  return TREE.nodes[handle] || null
}

export function nodeName(node: CategoryNode, _locale?: Locale): string {
  // XLMarket = EN-only (CLAUDE.md HARD RULE #1). Locale param kept for
  // back-compat but ignored — always return the English name.
  return node.name_en
}

export function nodeImage(node: CategoryNode | null): string | null {
  return node?.image_path ?? null
}

/** Resolve breadcrumb ancestors from root → immediate parent (excludes node itself). */
export function getAncestors(handle: string): CategoryNode[] {
  const out: CategoryNode[] = []
  let cur = getNode(handle)
  if (!cur) return out
  while (cur.parent_handle) {
    const parent = getNode(cur.parent_handle)
    if (!parent) break
    out.unshift(parent)
    cur = parent
  }
  return out
}

/** The L1 ancestor of a node (or the node itself if already L1). Returns null for unknown handle. */
export function getL1Ancestor(handle: string): CategoryNode | null {
  let cur = getNode(handle)
  while (cur) {
    if (cur.level === 1) return cur
    if (!cur.parent_handle) return null
    cur = getNode(cur.parent_handle)
  }
  return null
}

/** Siblings under the same parent, excluding the node itself. */
export function getSiblings(handle: string): CategoryNode[] {
  const node = getNode(handle)
  if (!node || !node.parent_handle) return []
  const parent = getNode(node.parent_handle)
  if (!parent) return []
  return parent.child_handles
    .filter((h) => h !== handle)
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null)
}

/** Direct children (L3 row when called from an L2 page). */
export function getChildren(handle: string): CategoryNode[] {
  const node = getNode(handle)
  if (!node) return []
  return node.child_handles
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null)
}

/** All L1 nodes in YAML order. */
export function getAllL1(): CategoryNode[] {
  return TREE.order
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null && n.level === 1)
}

/**
 * All L1 nodes are visible in the MegaMenu.
 * Spec §3.1.1 (revised 2026-04-18 by user): no category may be hidden by
 * product-count or subcategory-count threshold. Only nodes whose full subtree
 * contains 0 in-stock products are hidden — enforced dynamically at carousel
 * and menu level via Meili facet counts, not by a static list here.
 */
export function getVisibleL1(): CategoryNode[] {
  return getAllL1()
}

/** Build the canonical breadcrumb trail for any handle — root → node inclusive. */
export function getBreadcrumbTrail(
  handle: string,
  _locale?: Locale
): Array<{ handle: string; name: string }> {
  // locale ignored — EN-only (CLAUDE.md HARD RULE #1).
  const node = getNode(handle)
  if (!node) return []
  const out: Array<{ handle: string; name: string }> = []
  for (const a of getAncestors(handle)) {
    out.push({ handle: a.handle, name: nodeName(a) })
  }
  out.push({ handle: node.handle, name: nodeName(node) })
  return out
}

/**
 * A child category node enriched with its Meili product count.
 * Used by the subcategory carousel (spec §3.5.4).
 */
export interface ChildWithCount extends CategoryNode {
  count: number
}

/**
 * Merge `getChildren(handle)` with a Meili facet distribution map and return
 * only children that actually have products (count > 0). Children are sorted
 * first by their original YAML/taxonomy order (preserved through
 * `child_handles`), then tie-broken by count descending. Sort stability is
 * guaranteed because we walk `child_handles` in order.
 *
 * Spec §3.5.4 + INV-25: zero-count children MUST NOT appear in the carousel.
 *
 * @param handle   current node handle
 * @param facetMap Meili `facetDistribution["taxonomy.ancestors"]` object —
 *                 keys are category handles, values are product counts.
 */
export function getChildrenWithProductCounts(
  handle: string,
  facetMap: Record<string, number>
): ChildWithCount[] {
  const children = getChildren(handle)
  const enriched: ChildWithCount[] = children.map((child) => ({
    ...child,
    count: facetMap[child.handle] ?? 0,
  }))
  // Filter 0-count children (INV-25).
  const visible = enriched.filter((c) => c.count > 0)
  // child_handles already carries the authored order. When two children share
  // an index we keep that order; we only tie-break by count desc when the
  // caller supplies counts that coincide on neighbouring positions. Use a
  // stable sort that preserves YAML order as the primary key by indexing
  // against the child_handles position.
  const node = getNode(handle)
  const orderIndex = new Map<string, number>()
  if (node) {
    node.child_handles.forEach((h, idx) => orderIndex.set(h, idx))
  }
  visible.sort((a, b) => {
    const ai = orderIndex.get(a.handle) ?? Number.MAX_SAFE_INTEGER
    const bi = orderIndex.get(b.handle) ?? Number.MAX_SAFE_INTEGER
    if (ai !== bi) return ai - bi
    return b.count - a.count
  })
  return visible
}

/**
 * Find the first handle from a candidate list that exists in the SSoT tree.
 * Used by the product page to pick a valid v3 handle from a product's
 * category_handles array (which may contain legacy strings).
 */
export function firstKnownHandle(candidates: string[]): CategoryNode | null {
  for (const h of candidates) {
    const node = getNode(h)
    if (node) return node
  }
  return null
}

/**
 * Total node count — useful for CI checks.
 */
export function totalNodes(): number {
  return TREE.order.length
}
