/**
 * category-tree.ts — SSoT-derived category hierarchy lookups for the
 * /kategooriad/[handle] page.
 *
 * Source of truth: backend/src/data/taxonomy.yaml
 * Snapshot:       storefront/lib/category-tree.generated.json
 *                 (regenerated by scripts/gen-category-tree.mjs)
 *
 * The page asks three questions per request:
 *   1. ancestor chain (breadcrumb)        — getAncestors()
 *   2. sibling list   (sidebar L2 list)   — getSiblings()
 *   3. children       (L3 thumbnail row)  — getChildren()
 *
 * All lookups are O(1) — the file is ~30 KB and loaded once at boot.
 */

import treeData from "./category-tree.generated.json"

export type Locale = "et" | "en"

export interface CategoryNode {
  handle: string
  name_en: string
  name_et: string
  level: 1 | 2 | 3
  parent_handle: string | null
  child_handles: string[]
}

interface TreeData {
  generated_at: string
  nodes: Record<string, CategoryNode>
  order: string[]
}

const TREE = treeData as TreeData

export function getNode(handle: string): CategoryNode | null {
  return TREE.nodes[handle] || null
}

export function nodeName(node: CategoryNode, locale: Locale): string {
  return locale === "en" ? node.name_en : node.name_et
}

/** Returns ancestors from root → immediate parent (excludes the node itself). */
export function getAncestors(handle: string): CategoryNode[] {
  const out: CategoryNode[] = []
  let cur = getNode(handle)
  if (!cur) return out
  while (cur.parent_handle) {
    const parent = getNode(cur.parent_handle)
    if (!parent) break
    out.unshift(parent)
    cur = parent
  }
  return out
}

/** Siblings under the same parent, excluding the node itself. */
export function getSiblings(handle: string): CategoryNode[] {
  const node = getNode(handle)
  if (!node || !node.parent_handle) return []
  const parent = getNode(node.parent_handle)
  if (!parent) return []
  return parent.child_handles
    .filter((h) => h !== handle)
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null)
}

/** Direct children (L3 row when called from an L2 page). */
export function getChildren(handle: string): CategoryNode[] {
  const node = getNode(handle)
  if (!node) return []
  return node.child_handles
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null)
}

/** All L1 nodes in YAML order (for the L1 page sibling list = "Other Departments"). */
export function getAllL1(): CategoryNode[] {
  return TREE.order
    .map((h) => getNode(h))
    .filter((n): n is CategoryNode => n !== null && n.level === 1)
}
