/**
 * outlet-labels.ts — SEISUND (Outlet) product-badge labels.
 *
 * Source of truth: backend/src/data/taxonomy.yaml (fixed_l2 mains → L2 buckets)
 * Snapshot:        storefront/lib/outlet-labels.generated.json
 *                  (regenerated by scripts/gen-category-tree.mjs)
 *
 * A product that belongs to an Outlet L2 (e.g. v4-outlet-rikutud-pakend) shows an
 * automatic condition badge ("Kahjustatud pakend" / "Defektiga toode" / "Leiunurk").
 * The badge is derived purely from the product's own category handles — no new data
 * field. It also explains cross-display: when an Outlet product is also listed in its
 * type category (e.g. Tuulegeneraatorid), the badge says WHY it is there.
 *
 * Client-safe: imports only the tiny labels snapshot, never the full category tree.
 */
import labelsDoc from "./outlet-labels.generated.json"

interface OutletLabel {
  et: string
  en: string
  main: string
}

const LABELS: Record<string, OutletLabel> =
  (labelsDoc as { labels?: Record<string, OutletLabel> }).labels || {}

/**
 * The SEISUND badge label for a product, given its category handles, or null when
 * the product is not in any Outlet L2. First matching handle wins (a product sits
 * in exactly one Outlet bucket in practice).
 */
export function getOutletLabel(
  handles: readonly string[] | undefined,
  locale?: string
): string | null {
  if (!handles) return null
  for (const h of handles) {
    const l = LABELS[h]
    if (l) return locale === "et" ? l.et : l.en
  }
  return null
}
