/**
 * outlet-labels.ts — SEISUND (Outlet) product badges.
 *
 * Source of truth: backend/src/data/taxonomy.yaml (fixed_l2 mains → L2 buckets)
 * Snapshot:        storefront/lib/outlet-labels.generated.json
 *                  (regenerated by scripts/gen-category-tree.mjs)
 *
 * An Outlet product carries TWO automatic, category-derived badges:
 *   1. GENERIC  — the SEISUND main label ("Outlet toode") — on every outlet product.
 *   2. SPECIFIC — its L2 bucket ("Kahjustatud pakend" / "Defektiga toode" / "Leiunurk").
 *
 * Both are derived purely from the product's own category handles (the Meili hit's
 * category_handles union) — NOT from the page that renders the card. So the badges
 * TRAVEL WITH THE PRODUCT: when an outlet product is cross-displayed in its type
 * category (Outlet = home, type = optional extra display), the badges come along and
 * explain why it is there. No new data field, no per-product code.
 *
 * Client-safe: imports only the tiny labels snapshot, never the full category tree.
 */
import labelsDoc from "./outlet-labels.generated.json"

interface L2Label {
  et: string
  en: string
  main: string
}
interface MainLabel {
  et: string
  en: string
}

const DOC = labelsDoc as {
  mains?: Record<string, MainLabel>
  labels?: Record<string, L2Label>
}
const MAINS: Record<string, MainLabel> = DOC.mains || {}
const LABELS: Record<string, L2Label> = DOC.labels || {}

const pick = (l: { et: string; en: string }, locale?: string): string =>
  locale === "et" ? l.et : l.en

export interface OutletBadges {
  /** Generic SEISUND label ("Outlet toode") — present on every outlet product. */
  generic: string | null
  /** Specific L2 bucket label ("Kahjustatud pakend") — present when the product sits in an L2. */
  specific: string | null
}

/**
 * The Outlet badges for a product, given its category handles. Returns both null
 * when the product is not in any Outlet bucket. First matching handle wins (a
 * product sits in exactly one Outlet bucket in practice). A product bound directly
 * to a SEISUND main (no L2) still gets the generic badge.
 */
export function getOutletBadges(
  handles: readonly string[] | undefined,
  locale?: string
): OutletBadges {
  if (!handles) return { generic: null, specific: null }
  let specific: string | null = null
  let generic: string | null = null
  let mainHandle: string | null = null
  for (const h of handles) {
    if (!specific && LABELS[h]) {
      specific = pick(LABELS[h], locale)
      mainHandle = LABELS[h].main
    }
    if (!generic && MAINS[h]) generic = pick(MAINS[h], locale)
  }
  if (!generic && mainHandle && MAINS[mainHandle]) {
    generic = pick(MAINS[mainHandle], locale)
  }
  return { generic, specific }
}

/** Back-compat single-label helper (specific L2 label, or null). */
export function getOutletLabel(
  handles: readonly string[] | undefined,
  locale?: string
): string | null {
  return getOutletBadges(handles, locale).specific
}
