import {
  UtensilsCrossed, Building2, Wrench, Flame, Zap, TreePine,
  Printer, Plug, Snowflake, Droplets, Warehouse, Car, Leaf, Fuel,
  Sparkles, ShieldCheck, Armchair, Scissors, Dumbbell, Ship,
  HeartPulse, Music, type LucideIcon,
} from "lucide-react"

export interface TaxonomyL1 {
  id: number
  slug: string
  name: string
  subs: string[]
  subSlugs: string[]
  extra: string[]
  meiliQuery: string
  prodNum: number
}

// 22 L1 categories — v3 taxonomy (approved 2026-04-16).
// Order follows B2B market research score: HoReCa #1, Laser/CNC #2, Printing #3.
export const TAXONOMY_V3: TaxonomyL1[] = [
  { id: 1, prodNum: 1, slug: "horeca-food-service", name: "HoReCa & Food Service",
    subs: ["Commercial Refrigeration","Commercial Cooking Equipment","Food Preparation Equipment","Bar & Beverage Service","Commercial Sinks & Washdown","Restaurant Storage & Shelving"],
    subSlugs: ["refrigerators","commercial-ovens","food-preparation","espresso-machines","commercial-sinks","restaurant-shelving"],
    extra: ["Restaurant Furniture","Kitchen HVAC & Air Curtains","Ice Machines","Display Cases","Bain-Maries"],
    meiliQuery: "commercial refrigeration ice machine restaurant" },
  { id: 5, prodNum: 5, slug: "laser-cnc-digital-fabrication", name: "Laser, CNC & Digital Fabrication",
    subs: ["CO2 Laser Engravers & Cutters","Diode Laser Engravers","CNC Routers & Mills","3D Printers","Laser & CNC Accessories","Rotary Attachments"],
    subSlugs: ["co2-laser-engraving-machine","two-axis-diode-laser-engraving-machine","cnc-milling-cutter","3d-printers","laser-engraving-machine-accessories","rotary-laser"],
    extra: ["CNC Spindles","Stepper Motors","Controller Boards","Dust Collection","Honeycomb Tables"],
    meiliQuery: "laser engraver CNC router 3D printer" },
  { id: 4, prodNum: 4, slug: "welding-metalworking", name: "Welding & Metalworking",
    subs: ["Welding & Cutting","Metal Lathes & Mills","Angle Grinders & Metal Cutting Tools","Hydraulic & Press Equipment","Welding Safety & Apparel","Motors, Drives & Parts"],
    subSlugs: ["welding-kits","metal-lathe","angle-grinder","hydraulic-press","welding-safety-apparel","motors-parts"],
    extra: ["Welding Wire & Rods","Sheet Metal Brakes","Milling Machines","Deburring Tools","Metal Bandsaw"],
    meiliQuery: "welding machine MIG TIG lathe grinder" },
  { id: 7, prodNum: 6, slug: "printing-packaging-signage", name: "Printing, Packaging & Signage",
    subs: ["Screen Printing & Heat Press","Vinyl Cutters & Plotters","Packaging & Sealing Equipment","Label Makers & Printers","Signage & Display","Paper & Document Handling"],
    subSlugs: ["heat-press-machine","vinyl-cutter","continuous-sealing-machines","label-makers","banner-display","paper-cutter"],
    extra: ["Cash Handling","Shrink Wrap Machines","Strapping Machines","Carton Sealers","Badge Makers"],
    meiliQuery: "heat press vinyl cutter screen printing" },
  { id: 8, prodNum: 8, slug: "electrical-energy", name: "Electrical & Energy",
    subs: ["Generators & Portable Power","Solar & Renewable Energy","Electrical Tools & Testing","Wiring, Conduit & Enclosures","Commercial & Industrial Lighting","Batteries & Charging"],
    subSlugs: ["portable-power-stations","solar-panels","electrical","wiring-devices-light-controls","commercial-lighting","batteries"],
    extra: ["Networking & Electronics","Distribution Boards","Cable Management","Transformers","Inverters"],
    meiliQuery: "generator solar panel inverter battery charger" },
  { id: 6, prodNum: 2, slug: "woodworking-carpentry", name: "Woodworking & Carpentry",
    subs: ["Stationary Woodworking Machines","Routers & Shaping","Woodworking Benches & Clamps","Drill Presses & Boring","Saw Accessories & Blades","Finishing & Sanding Tools"],
    subSlugs: ["woodworking-table-saws","routers-bits-accessories","woodworking-benches","drill-press","saw-blades","belt-sander"],
    extra: ["Table Saws","Band Saws","Planers","Scroll Saws","Doweling Jigs"],
    meiliQuery: "table saw band saw planer router woodworking" },
  { id: 2, prodNum: 7, slug: "construction-building", name: "Construction & Building",
    subs: ["Concrete, Masonry & Drywall","Ladders, Scaffolding & Work Platforms","Roofing & Insulation","Flooring Installation","Decking, Fencing & Structural Hardware","Paint, Caulk & Surface Finishing"],
    subSlugs: ["concrete-cement-masonry","scaffolding","roofing","flooring","decking","paint"],
    extra: ["Door Hardware & Garage Doors","Tile Cutters","Surveying Equipment","Safety Netting","Formwork"],
    meiliQuery: "scaffold ladder tile cutter concrete mixer" },
  { id: 15, prodNum: 15, slug: "cleaning-janitorial", name: "Cleaning & Janitorial",
    subs: ["Floor Care Equipment","Janitorial Supplies & Carts","Hand Dryers & Washroom Equipment","Waste & Recycling","Industrial Vacuums","Carpet Extractors"],
    subSlugs: ["floor-care","janitorial-carts","hand-dryers","waste-disposal-systems","vacuum-cleaners","carpet"],
    extra: ["Sweepers","Sanitizer Dispensers","Mop Systems","Window Cleaning","Air Fresheners"],
    meiliQuery: "industrial vacuum floor scrubber hand dryer" },
  { id: 3, prodNum: 2, slug: "hand-power-tools", name: "Hand & Power Tools",
    subs: ["Power Tools","Hand Tools","Air Compressors & Pneumatic Tools","Measuring & Layout Tools","Power Tool Accessories & Bits","Tool Storage & Cases"],
    subSlugs: ["power-tools","hand-tools","air-compressors","measuring-rods","power-tool-accessories","tool-storage"],
    extra: ["Impact Wrenches","Heat Guns","Rotary Tools","Clamps & Vises","Riveting Tools"],
    meiliQuery: "drill impact wrench air compressor tool" },
  { id: 14, prodNum: 24, slug: "fuel-lubrication-fluid", name: "Fuel, Lubrication & Fluid Management",
    subs: ["Fuel Transfer Pumps","Oil & Lubrication Equipment","Drum & Container Handling","Dewatering & Industrial Pumps","Chemical Transfer Equipment","Fuel Nozzles"],
    subSlugs: ["ac-fuel-transfer-pumps","oil-drains","drum-handling-equipment","dewatering-pump","chemical-transfer","fuel-filters"],
    extra: ["Flow Meters","Grease Guns","Spill Containment","Fuel Tanks","Hose Reels"],
    meiliQuery: "fuel transfer pump oil lubrication drum" },
  { id: 13, prodNum: 14, slug: "outdoor-power-landscaping", name: "Outdoor Power & Landscaping",
    subs: ["Outdoor Power Equipment","Pressure Washers","Garden Tools & Landscaping Supplies","Outdoor Cooking & Grilling","Outdoor Heating","Outdoor Decor & Structures"],
    subSlugs: ["outdoor-power-equipment","pressure-washers","garden-fork","outdoor-cooking","outdoor-heating","outdoor-decor"],
    extra: ["Pet & Livestock Supplies","Log Splitters","Stump Grinders","Irrigation Systems","ATV Accessories"],
    meiliQuery: "pressure washer chainsaw lawn mower garden" },
  { id: 11, prodNum: 11, slug: "warehousing-material-handling", name: "Warehousing & Material Handling",
    subs: ["Hoists, Cranes & Lifting","Forklifts & Pallet Equipment","Carts, Dollies & Hand Trucks","Industrial Shelving & Racking","Workbenches & Tool Storage","Strapping, Chains & Securing"],
    subSlugs: ["engine-hoists","forklifts-attachments","platform-trucks-dollies","industrial-shelving","workbenches","strapping-band"],
    extra: ["Outdoor & Yard Storage","Winches","Lift Tables","Drum Handlers","Conveyor Rollers"],
    meiliQuery: "hoist crane pallet jack shelving workbench" },
  { id: 9, prodNum: 10, slug: "hvac-climate-control", name: "HVAC & Climate Control",
    subs: ["Air Conditioners & Mini Splits","Heaters","Fans & Ventilation","Ducting, Grilles & HVAC Supplies","Air Quality & Purification","Dehumidifiers & Evaporative Coolers"],
    subSlugs: ["mini-split-air-conditioners","heaters","fans","ducting-venting","air-quality-testers","evaporative-coolers"],
    extra: ["Fireplaces & Heating Appliances","Thermostats","Heat Exchangers","Radiant Heaters","Ceiling Fans"],
    meiliQuery: "air conditioner mini split heater fan ventilation" },
  { id: 10, prodNum: 9, slug: "plumbing-water-systems", name: "Plumbing & Water Systems",
    subs: ["Water Pumps","Pipes, Fittings & Valves","Plumbing Tools","Water Heaters","Water Filtration & Softening","Bathroom Fixtures"],
    subSlugs: ["water-pumps","pipes-and-fittings","plumbing","water-heaters","vacuum-cleaners","bathroom-sinks"],
    extra: ["Kitchen Plumbing","Drain Cleaners","Water Tanks","Pressure Regulators","Expansion Vessels"],
    meiliQuery: "water pump pipe fitting water heater filter" },
  { id: 16, prodNum: 13, slug: "safety-security-workwear", name: "Safety, Security & Workwear",
    subs: ["Personal Protective Equipment","Traffic & Site Safety","Locks, Safes & Access Control","Work Boots & Footwear","Work Clothing & Outerwear","Safety Glasses"],
    subSlugs: ["personal-protective-equipment","safety-traffic-control","door-locks","work-boots","workwear","safety-glasses"],
    extra: ["Ear Protection","Respiratory Masks","First Aid Kits","Fire Extinguishers","Lockout/Tagout"],
    meiliQuery: "safety boots helmet gloves safe lock PPE" },
  { id: 12, prodNum: 3, slug: "automotive-workshop", name: "Automotive & Workshop",
    subs: ["Vehicle Lifts & Shop Equipment","Mechanics & Diagnostic Tools","Jacks & Lifting","Towing & Recovery","Truck & Cargo Accessories","Auto Parts & Replacement"],
    subSlugs: ["car-lifts","mechanics-tools","air-jacks","towing-mirrors","truck-accessories","auto-parts"],
    extra: ["RV & Specialty Vehicle Supplies","Car Detailing & Care","Tire Changers","Wheel Balancers","Brake Tools"],
    meiliQuery: "car jack vehicle lift tire changer mechanic tool" },
  { id: 18, prodNum: 16, slug: "salon-spa-wellness", name: "Salon, Spa & Wellness",
    subs: ["Barber & Salon Chairs","Shampoo Stations & Salon Furniture","Massage Tables & Spa Equipment","Personal Care Appliances","Manicure & Nail Equipment","Facial Steamers"],
    subSlugs: ["barber-chairs","shampoo-sink","massage-tables","personal-care-appliances","manicure-table","facial-steamers"],
    extra: ["Waxing Equipment","Salon Trolleys","Towel Warmers","Sterilizers","Pedicure Chairs"],
    meiliQuery: "barber chair massage table salon shampoo station" },
  { id: 17, prodNum: 17, slug: "office-commercial-interiors", name: "Office & Commercial Interiors",
    subs: ["Office Furniture","Meeting & Lobby Furniture","Door & Cabinet Hardware","Interior Lighting","Bathroom Accessories","Home Decor & Window Treatments"],
    subSlugs: ["home-office-furniture","lobby-furniture","door-hardware","interior-lighting","bathroom-accessories","home-decor"],
    extra: ["TV Mounts","Cable Management","Monitor Arms","Desk Organizers","Filing Cabinets"],
    meiliQuery: "office chair desk TV mount cabinet furniture" },
  { id: 21, prodNum: 12, slug: "health-medical-supply", name: "Health & Medical Supply",
    subs: ["Medical Equipment & Furniture","Mobility Aids","Bathroom Safety","Teaching & Demonstration Models","Wellness & Skin Care","Wheelchairs"],
    subSlugs: ["medical-chairs","mobility-aids","bathroom-safety","human-body-teaching-models","skin-care","wheelchairs"],
    extra: ["Walkers & Rollators","Hospital Beds","Exam Tables","Grab Bars","Shower Seats"],
    meiliQuery: "wheelchair walker grab bar medical exam table" },
  { id: 19, prodNum: 18, slug: "fitness-sports-recreation", name: "Fitness, Sports & Recreation",
    subs: ["Gym Equipment","Team Sports Equipment","Gym Flooring & Mats","Trampolines","Playground & Outdoor Play","Cycling"],
    subSlugs: ["gym-mats","sports-equipment","gym-flooring","trampolines","playground-sets","cycling"],
    extra: ["Hunting, Fishing & Archery","Bounce Houses","Dance Poles","Boxing Bags","Climbing Walls"],
    meiliQuery: "gym equipment trampoline dumbbell treadmill bike" },
  { id: 20, prodNum: 21, slug: "boating-camping-outdoor", name: "Boating, Camping & Outdoor Adventure",
    subs: ["Boat Parts & Marine Hardware","Inflatable Boats & Kayaks","Water Sports","Camping Gear","Canopy Tents & Event Shelters","Outdoor Hobbies"],
    subSlugs: ["boat-hardware","inflatable-boats","water-sports","camping-gear","canopy-tents","outdoor-hobbies"],
    extra: ["Marine Electronics","Boat Covers","Anchor Systems","Navigation Lights","Fishing Rod Holders"],
    meiliQuery: "inflatable boat kayak canopy tent camping" },
  { id: 22, prodNum: 23, slug: "music-entertainment", name: "Music & Entertainment",
    subs: ["Guitars & String Instruments","Keyboards & Electronic Instruments","Drums & Percussion","Stage, Dance & Performance","Game Room & Entertainment","Instrument Storage & Cases"],
    subSlugs: ["guitars","electronic-keyboards","drums-percussion","stage-lighting","game-room","musical-instrument-storage"],
    extra: ["PA Systems","DJ Equipment","Microphones","Lighting Effects","Pool Tables"],
    meiliQuery: "guitar keyboard drum stage lighting pool table" },
]

// v3 L1 slug → Lucide icon
export const V3_ICONS: Record<string, LucideIcon> = {
  "horeca-food-service": UtensilsCrossed,
  "laser-cnc-digital-fabrication": Zap,
  "welding-metalworking": Flame,
  "printing-packaging-signage": Printer,
  "electrical-energy": Plug,
  "woodworking-carpentry": TreePine,
  "construction-building": Building2,
  "cleaning-janitorial": Sparkles,
  "hand-power-tools": Wrench,
  "fuel-lubrication-fluid": Fuel,
  "outdoor-power-landscaping": Leaf,
  "warehousing-material-handling": Warehouse,
  "hvac-climate-control": Snowflake,
  "plumbing-water-systems": Droplets,
  "safety-security-workwear": ShieldCheck,
  "automotive-workshop": Car,
  "salon-spa-wellness": Scissors,
  "office-commercial-interiors": Armchair,
  "health-medical-supply": HeartPulse,
  "fitness-sports-recreation": Dumbbell,
  "boating-camping-outdoor": Ship,
  "music-entertainment": Music,
}
